import matplotlib.pyplot as plt
import torch
import numpy as np

def visualize_routes(depot, nodes, sequence, title="VRP Solution"):
    """
    Visualize the routes generated by the model.
    
    Args:
        depot: [x, y] coordinates of the depot.
        nodes: List of [x, y] coordinates for customers.
        sequence: List of indices (integers) representing the path.
        title: Title of the plot.
    """
    # --- SAFETY FIX: Data Type Handling ---
    # Ensure everything is a simple Python list/number, not a GPU Tensor
    if isinstance(depot, torch.Tensor): depot = depot.cpu().numpy()
    if isinstance(nodes, torch.Tensor): nodes = nodes.cpu().numpy()
    if isinstance(sequence, torch.Tensor): sequence = sequence.cpu().numpy()
    
    # --------------------------------------

    plt.figure(figsize=(10, 6))
    
    # 1. Plot Customers (Blue Dots)
    # Separate x and y for plotting
    # Handle both list of lists and numpy arrays
    node_x = [n[0] for n in nodes]
    node_y = [n[1] for n in nodes]
    
    plt.scatter(node_x, node_y, c='blue', label='Customers')
    
    # 2. Plot Depot (Red Star)
    plt.scatter(depot[0], depot[1], c='red', s=200, marker='*', label='Depot')
    
    # 3. Construct Path
    # Combine all coords: Index 0 is Depot, 1..N are customers
    # We need to be careful about combining lists vs arrays
    if isinstance(nodes, np.ndarray):
        all_coords = np.vstack([np.array(depot).reshape(1, 2), nodes])
    else:
        all_coords = [depot] + nodes
    
    # 4. Draw the Lines (The Route)
    current_pos = depot
    
    # Loop through the sequence of visits
    for next_node_idx in sequence:
        # If index is 0, it means return to depot
        # If index > 0, it means visit customer (index 1 in 'nodes' is index 1 in all_coords)
        next_pos = all_coords[int(next_node_idx)]
        
        # Draw line from Current -> Next
        plt.plot([current_pos[0], next_pos[0]], [current_pos[1], next_pos[1]], c='green', alpha=0.6, linewidth=2)
        
        current_pos = next_pos
        
    # 5. Formatting
    plt.title(title)
    plt.legend()
    plt.xlabel("X Coordinate")
    plt.ylabel("Y Coordinate")
    plt.grid(True)
    
    # Show the plot
    plt.show()